### ISSUE TITLE
关于绘制fc_avg.png和fct_cdf.png两个结果图出现的问题

### ISSUE THREAD

**Issue by alemfight** [ErianArcher/t-dctcp#1]
你好,我是英国利兹大学在读本科生.
无意间在GITHUB上看到了您的TDCTCP的测试项目,我对它很感兴趣,并且按照您的步骤复制了结果.
但是我发现在绘制fc_avg.png和fct_cdf.png两个结果图的时候出现了问题,结果图中没有任何数据
我查看了记录结果数据的txt文件,发现里面没有数据,.
我又查看了源代码发现里面这样两句
cmd = "curl -o /dev/null -w%{time_connect}:%{time_starttransfer}:%{time_total} -s -d @/home/erian/Documents/graduation_design/data/"
和
hosts[0].popen('python /home/erian/Documents/graduation_design/PostHTTPServer.py 80', shell=True)
这里面的文件路径是您电脑上的路径.
不知您是否可以提供一下以上两个文件,我将万分感激.
十分感谢.

**Comment by ErianArcher** [comment]
@alemfight 非常抱歉隔了这么久才回复您,最近没怎么看github所以没有看到您的消息.现在我把您所需要的PostHTTPServer.py打包上传在该回复的附件中,然后你去把exp.py下第406行路径改一下就可以用了.
而还有exp.py下第299和354行的输入路径也需要更改一下,因为当时用了绝对路径,这两个是用来模拟不同大小数据流的,你可以改成你本机的绝对路径.
对于我的疏忽,我表示非常抱歉.

[PostHTTPServer.zip](https://github.com/ErianArcher/t-dctcp/files/2260051/PostHTTPServer.zip)

**Comment by alemfight** [comment]
谢谢您的回复,万分感谢.

**Comment by alemfight** [comment]
你好,您上传的压缩包里面没有模拟不同数据流的文件,我不太清楚这两个具体该怎么模拟,可以请您再追加上传一下吗,谢谢

**Comment by ErianArcher** [comment]
@alemfight 我已经更新README以及把生成data文件的python文件上传到github上了,你可以运行项目目录下的gen_bytes.py生成data目录

**Comment by ErianArcher** [comment]
@alemfight 如果对于这个issue提出的问题没有什么问题的话,我就关闭这个issue啦

**Comment by alemfight** [comment]
真的太谢谢你了,问题解决了,谢谢谢谢,可以关闭了
